apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
  labels:
    app: registration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration-container
          image: registration-form:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
  labels:
    app: registration
spec:
  type: NodePort
  selector:
    app: registration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
